services:
  jupyter:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    restart: always
    ports:
      - 8888:8888
    volumes:
      - ..:/workspace
    environment:
      - PYTHONIOENCODING=utf-8
      - TZ=Asia/Tokyo
      - LANG=ja_JP.UTF-8
      - LANGUAGE=ja_JP:ja
      - LC_ALL=ja_JP.UTF-8
    command: sleep infinity
