services:
  jupyter:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ..:/workspace
    command: jupyterlab --NotebookApp.token=''
